### GET plaintext
http://127.0.0.1:3000/plaintext

### GET JSON response
http://127.0.0.1:3000/jsonresponse

### GET HTML response
http://127.0.0.1:3000/htmlres

### POST request 
POST http://127.0.0.1:3000/postdata HTTP/1.1
content-type: application/json

{
    "name": "JSON From frontend",
    "time": "Jan 11 1999"
}

// Express JS routes

### get all sales by all users (optional query params)
http://127.0.0.1:3000/sales

### create a new sales entry
http://127.0.0.1:3000/users/user-029dsdd/sales/00fdxb21e

### 
http://127.0.0.1:3000/users/sales?bla=ssd